// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamarinForms.VisualDebug.VsixExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "XamarinForms.VisualDebug.VsixExtension.af76ba3d-7aa9-497c-bbc0-f3213cf0aad8";
        public const string Name = "XamarinForms.VisualDebug";
        public const string Description = @"An extension to view the visual heirarchy of your Xamarin app pages as an interactive tree diagram at runtime";
        public const string Language = "en-US";
        public const string Version = "0.0.4";
        public const string Author = "David Thompson";
        public const string Tags = "Xamarin XamarinForms visual heirarchy debug tree live VisualDebug";
    }
}
