// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamarinForms.VisualDebug.VsixExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVISXPackageString = "8992fdc0-9998-4c7e-840b-5167d167b548";
        public static Guid guidVISXPackage = new Guid(guidVISXPackageString);

        public const string guidVISXPackageCmdSetString = "ce2dea66-c029-493e-bed4-a21e6f3c5022";
        public static Guid guidVISXPackageCmdSet = new Guid(guidVISXPackageCmdSetString);

        public const string guidImagesString = "2172c3cc-8a94-4b2c-92c0-ec5ab3b3561d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TreeViewToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}